#!/usr/bin/env bash

echo "Note! you should really consider using './manage deploy sam' in the root of the repo."

#TMP_FNAME="cdk-tmp-$(date +%s)"

set -e
#cdk synth > $TMP_FNAME
#echo "# Autogenerated!" > ../template.yaml
#cat $TMP_FNAME >> ../template.yaml
#rm $TMP_FNAME
#echo "Done!"

cd $(dirname "$0")/../../../../ && \
  ./manage build sam

