#!/usr/bin/env bash

if [ ! -d '.venv' ]; then
    if which virtualenv >/dev/null 2>&1; then
        echo '' > /dev/null
    else
        pip3 install virtualenv
    fi

    virtualenv .venv
fi

source .venv/bin/activate

python3 -m py_app_manager "$@"
